property_type: Appartement
city: Toulouse
surface: 20
dpe: A
property_price: 100000
agency_fee_rate: 8.0
notary_fee_rate: 8.5
renovation_cost: 0
furniture_cost: 3000
down_payment: 10000
loan_rate: 3.5
loan_duration: 25
monthly_rent: 600
annual_expenses: 1500
rent_increase_rate: 1.0
resale: 2.5
