type: Appartement
ville: Toulouse
surface: 20
dpe: A
ges: A
prix_bien: 100000
frais_agence: 6
frais_notaire: 8
travaux: 0
meubles: 3000
apport: 10000
taux_emprunt: 3.5
duree_emprunt: 25
loyer: 600
charges: 1500
aug_loyer: 0.0
revente: 1